import { createSvgSlide } from './svg-slide-renderer';
import type { SlideDefinition } from '~/pkgs/deck';

// Slide titles based on common presentation patterns and content analysis
const slideMetadata = [
	{ number: 1, title: 'Opening Logo' },
	{ number: 2, title: 'Presentation Deck Template' },
	{ number: 3, title: 'Slide 3' },
	{ number: 4, title: 'Section Title' },
	{ number: 5, title: 'Slide 5' },
	{ number: 6, title: 'Slide 6' },
	{ number: 7, title: 'Logo Examples' },
	{ number: 8, title: 'Slide 8' },
	{ number: 9, title: 'Slide 9' },
	{ number: 10, title: 'Slide 10' },
	{ number: 11, title: 'Logo Variations' },
	{ number: 12, title: 'Slide 12' },
	{ number: 13, title: 'Slide 13' },
	{ number: 14, title: 'Slide 14' },
	{ number: 15, title: 'Slide 15' },
	{ number: 16, title: 'Slide 16' },
	{ number: 17, title: 'Slide 17' },
	{ number: 18, title: 'Slide 18' },
	{ number: 19, title: 'Slide 19' },
	{ number: 20, title: 'Slide 20' },
	{ number: 21, title: 'Slide 21' },
	{ number: 22, title: 'Slide 22' },
	{ number: 23, title: 'Slide 23' },
	{ number: 24, title: 'Slide 24' },
	{ number: 25, title: 'Slide 25' },
	{ number: 26, title: 'Slide 26' },
	{ number: 27, title: 'Slide 27' },
	{ number: 28, title: 'Slide 28' },
	{ number: 29, title: 'Slide 29' },
	{ number: 30, title: 'Slide 30' },
	{ number: 31, title: 'Slide 31' },
	{ number: 32, title: 'Slide 32' },
	{ number: 33, title: 'Slide 33' },
	{ number: 34, title: 'Slide 34' },
	{ number: 35, title: 'Slide 35' },
	{ number: 36, title: 'Slide 36' },
	{ number: 37, title: 'Slide 37' },
	{ number: 38, title: 'Slide 38' },
	{ number: 39, title: 'Slide 39' },
	{ number: 40, title: 'Slide 40' },
	{ number: 41, title: 'Slide 41' },
	{ number: 42, title: 'Slide 42' },
	{ number: 43, title: 'Slide 43' },
	{ number: 44, title: 'Slide 44' },
	{ number: 45, title: 'Slide 45' },
	{ number: 46, title: 'Slide 46' },
	{ number: 47, title: 'Slide 47' },
	{ number: 48, title: 'Slide 48' },
	{ number: 49, title: 'Slide 49' },
	{ number: 50, title: 'Slide 50' },
	{ number: 51, title: 'Slide 51' },
	{ number: 52, title: 'Slide 52' },
	{ number: 53, title: 'Slide 53' },
	{ number: 54, title: 'Slide 54' },
	{ number: 55, title: 'Slide 55' },
	{ number: 56, title: 'Q&A' },
	{ number: 57, title: 'Slide 57' },
];

// Generate all slide definitions
export const VercelPresentationSlides: SlideDefinition[] = slideMetadata.map(({ number, title }) =>
	createSvgSlide({
		slideNumber: number,
		title,
		notes: `Original Vercel presentation slide ${number}: ${title}`,
	})
);

// Export individual slides for specific use
export const [
	Slide01Opening,
	Slide02PresentationDeck,
	Slide03,
	Slide04SectionTitle,
	Slide05,
	Slide06,
	Slide07LogoExamples,
	Slide08,
	Slide09,
	Slide10,
	Slide11LogoVariations,
	Slide12,
	Slide13,
	Slide14,
	Slide15,
	Slide16,
	Slide17,
	Slide18,
	Slide19,
	Slide20,
	Slide21,
	Slide22,
	Slide23,
	Slide24,
	Slide25,
	Slide26,
	Slide27,
	Slide28,
	Slide29,
	Slide30,
	Slide31,
	Slide32,
	Slide33,
	Slide34,
	Slide35,
	Slide36,
	Slide37,
	Slide38,
	Slide39,
	Slide40,
	Slide41,
	Slide42,
	Slide43,
	Slide44,
	Slide45,
	Slide46,
	Slide47,
	Slide48,
	Slide49,
	Slide50,
	Slide51,
	Slide52,
	Slide53,
	Slide54,
	Slide55,
	Slide56QandA,
	Slide57,
] = VercelPresentationSlides;